// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line ../../pkg/templates/index.qtpl:1
package templates

//line ../../pkg/templates/index.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line ../../pkg/templates/index.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line ../../pkg/templates/index.qtpl:2
type IndexPage struct {
	BasePage
}

//line ../../pkg/templates/index.qtpl:7
func (p *IndexPage) StreamHead(qw422016 *qt422016.Writer) {
//line ../../pkg/templates/index.qtpl:7
	qw422016.N().S(`
`)
//line ../../pkg/templates/index.qtpl:9
	p.BasePage.StreamHead(qw422016)
//line ../../pkg/templates/index.qtpl:9
	qw422016.N().S(`<link rel="stylesheet" href="/css/index.css?`)
//line ../../pkg/templates/index.qtpl:10
	qw422016.E().S(p.AssetsVersion)
//line ../../pkg/templates/index.qtpl:10
	qw422016.N().S(`">`)
//line ../../pkg/templates/index.qtpl:11
	qw422016.N().S(`
`)
//line ../../pkg/templates/index.qtpl:12
}

//line ../../pkg/templates/index.qtpl:12
func (p *IndexPage) WriteHead(qq422016 qtio422016.Writer) {
//line ../../pkg/templates/index.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/templates/index.qtpl:12
	p.StreamHead(qw422016)
//line ../../pkg/templates/index.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/templates/index.qtpl:12
}

//line ../../pkg/templates/index.qtpl:12
func (p *IndexPage) Head() string {
//line ../../pkg/templates/index.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/templates/index.qtpl:12
	p.WriteHead(qb422016)
//line ../../pkg/templates/index.qtpl:12
	qs422016 := string(qb422016.B)
//line ../../pkg/templates/index.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/templates/index.qtpl:12
	return qs422016
//line ../../pkg/templates/index.qtpl:12
}

//line ../../pkg/templates/index.qtpl:14
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line ../../pkg/templates/index.qtpl:14
	qw422016.N().S(`
`)
//line ../../pkg/templates/index.qtpl:15
	qw422016.N().S(`<body><main class="index"><div class="index__container"><div class="header"><div class="header__content"><h1 class="header__title"><span>Routinie</span></h1></div></div><footer class="footer"><div class="footer__content"><div class="footer__text"><p><span>Made with love and passion by </span><a target="_blank" href="https://alwxdev.com">Alexander Pantiukhov</a><span> in 2022.</span></p></div></div></footer></div></main></body>`)
//line ../../pkg/templates/index.qtpl:40
	qw422016.N().S(`
`)
//line ../../pkg/templates/index.qtpl:41
}

//line ../../pkg/templates/index.qtpl:41
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line ../../pkg/templates/index.qtpl:41
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/templates/index.qtpl:41
	p.StreamBody(qw422016)
//line ../../pkg/templates/index.qtpl:41
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/templates/index.qtpl:41
}

//line ../../pkg/templates/index.qtpl:41
func (p *IndexPage) Body() string {
//line ../../pkg/templates/index.qtpl:41
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/templates/index.qtpl:41
	p.WriteBody(qb422016)
//line ../../pkg/templates/index.qtpl:41
	qs422016 := string(qb422016.B)
//line ../../pkg/templates/index.qtpl:41
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/templates/index.qtpl:41
	return qs422016
//line ../../pkg/templates/index.qtpl:41
}

//line ../../pkg/templates/index.qtpl:43
func (p *IndexPage) StreamHTMLClass(qw422016 *qt422016.Writer) {
//line ../../pkg/templates/index.qtpl:43
	qw422016.N().S(`routinie routinie--full-height`)
//line ../../pkg/templates/index.qtpl:43
}

//line ../../pkg/templates/index.qtpl:43
func (p *IndexPage) WriteHTMLClass(qq422016 qtio422016.Writer) {
//line ../../pkg/templates/index.qtpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line ../../pkg/templates/index.qtpl:43
	p.StreamHTMLClass(qw422016)
//line ../../pkg/templates/index.qtpl:43
	qt422016.ReleaseWriter(qw422016)
//line ../../pkg/templates/index.qtpl:43
}

//line ../../pkg/templates/index.qtpl:43
func (p *IndexPage) HTMLClass() string {
//line ../../pkg/templates/index.qtpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line ../../pkg/templates/index.qtpl:43
	p.WriteHTMLClass(qb422016)
//line ../../pkg/templates/index.qtpl:43
	qs422016 := string(qb422016.B)
//line ../../pkg/templates/index.qtpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line ../../pkg/templates/index.qtpl:43
	return qs422016
//line ../../pkg/templates/index.qtpl:43
}
